# -*- coding: utf-8 -*-
{
    "name": "HIS",
    "summary": """
        Common module for HIS system""",
    "description": """
        Common module for HIS system
    """,
    "author": "UIC Group",
    "website": "https://uic.group",
    "category": "module_category_services",
    "version": "16.0.1.2.7",
    "license": "LGPL-3",
    "depends": [
        "base",
        "redis_session",
        "his_theme",
        "his_hr",
        "mail",
        "multitab",
        # "x2many_multiview",
        "new_calendar",
        "product",
        "form_wo_cp",
        "muk_web_theme",
        "portal_odoo_debranding",
        "remove_odoo_enterprise",
        "disable_odoo_online",
        "legion_webcam_image",
        "web_dialog_size",
        "web_save_discard_button",
        "web_remember_tree_column_width",
        "web_ir_actions_act_multi",
        "web_ir_actions_act_window_message",
        "base_search_fuzzy",
        "loyalty",
        "sale_loyalty",
        "account",
        "odoo_reportbro",
        "uom",
        "l10n_uz",
        "account_usability",
        "maintenance",
        "base_automation",
        "sale",
        "crm",
        "sale_crm",
        "auto_refresh",
        "base_user_role",
        "base_user_role_history",
        "base_global_discount",
        "queue_job",
        "queue_job_cron",
        "queue_job_batch",
        "base_fontawesome",
        "account_invoice_refund_reason",
        "account_invoice_refund_line_selection",
        "account_invoice_refund_link",
        "web_m2x_options",
        "sale_discount_display_amount",
        # 'sale_order_partner_no_autofollow',
        "fastapi",
        "hr_skills",
        "menu_icon_set",
        "base_tier_validation",
        "base_tier_validation_server_action",
        "base_menu_visibility_restriction",
        "web_select_all_companies",
        "auditlog",
        "stock",
    ],
    # "demo": [
    #     "demo/patient.xml",
    # ],
    "data": [
        # security file
        "security/groups.xml",
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/roles.xml",
        "security/report_security.xml",
        # data
        # "data/category_base.xml",
        "data/patient_for_call_center.xml",
        "data/paper_format.xml",
        "data/cashier_session_sequence.xml",
        # "data/models_for_emr.xml",
        "data/weekdays.xml",
        "data/his.diagnosis_category.csv",
        "data/his.diagnosis.csv",
        "data/uom_data.xml",
        "data/product_type.xml",
        "data/cron.xml",
        "data/queue_job.xml",
        "data/his_cancel_cause.xml",
        "data/doctor_schedule_visit_type.xml",
        "data/doctor_appointment_type.xml",
        "data/auto_archive_old_visits.xml",
        "data/res_partner_category.xml",
        "data/visit_tags.xml",
        "data/services_default.xml",
        "data/hr_resume_data.xml",
        "data/server_actions.xml",
        "data/hr_employee_company_automation.xml",
        "data/action_open_discount_wizard.xml",
        "data/action_print_payment_history.xml",
        "data/action_change_invoice_partner.xml",
        "data/referral_source_category.xml",
        "data/automated_action_recalculate_visit_type.xml",
        # core
        "views/core/menu.xml",
        "views/core/user.xml",
        "views/core/login.xml",
        "views/core/layout.xml",
        "data/res_state_district.xml",
        "data/res_district_neighborhood.xml",
        "views/deposit_journal.xml",
        "views/core/auth_totp.xml",
        # doctor
        "views/diagnosis.xml",
        "views/amb_list.xml",
        "views/visits_and_orders.xml",
        "views/referral_cabinet.xml",

        # patient
        "views/patient.xml",
        "views/patient_file.xml",
        "views/patient_visit.xml",
        "views/patient_visit_2.xml",
        "wizard/xml/patient/patient_merge_wizard.xml",
        "wizard/xml/patient/patient_visit_merge_wizard.xml",
        "wizard/xml/patient/clear_test_data_wizard.xml",
        "views/change_doctor_wizard.xml",
        "views/patients_with_deposit.xml",
        # account
        "views/account/account_move.xml",
        "views/account/account_payment.xml",
        "views/account/account_analytic_distribution_model_views.xml",
        "views/account/account_payment_view.xml",
        "views/account/analytic_account.xml",
        # payment
        # "views/payment/payment_transaction.xml",
        "wizard/xml/doctor/share_bonus_recalc_wizard.xml",
        "views/payment/doctor_share_bonus.xml",
        "views/payment/share_bonus_recalc_job_views.xml",
        "views/payment/order_detail.xml",
        "views/payment/surgery.xml",
        "views/payment/surgery_category.xml",
        "views/payment/sale_order_line.xml",
        "views/payment/sale_order_views.xml",
        "views/payment/payment_history.xml",
        "views/payment/payment_notification_history_view.xml",
        "wizard/xml/payment/send_payment_url_wizard_view.xml",
        "wizard/xml/payment/for_temporary_use.xml",
        # users
        "views/res_users.xml",
        # mail
        "views/mail_channel_views.xml",
        # patient_body_measurement
        "views/patient_body_measurement.xml",
        # employee
        "views/employee/job.xml",
        "views/employee/hr_employee.xml",
        "views/employee/virtual_doctor.xml",
        # common
        "views/common/cancel_cause.xml",
        "views/common/caution.xml",
        "views/common/country.xml",
        "views/common/unit_pack_type.xml",
        "views/common/referral_source.xml",
        # "views/common/district.xml",
        # "views/common/mahalla.xml",
        "views/common/nationality.xml",
        "views/common/his_equipment.xml",
        "views/common/prescription_instruction.xml",
        "views/common/prescription_template.xml",
        "views/common/position_type_service_category.xml",
        "views/common/comments_template.xml",
        # "views/common/report_category.xml", keyinroq yana ko'rib chiqiladi
        # uom
        "views/common/uom.xml",
        # service
        "views/service/gtin.xml",
        "views/service/room.xml",
        "views/service/room_type.xml",
        "views/service/doctor_fee.xml",
        "views/service/doctor_schedule.xml",
        "views/service/working_periods_views.xml",
        "views/service/product_type.xml",
        "views/service/product_category.xml",
        "views/service/product_product.xml",
        "views/service/product_nnm.xml",
        "views/service/prescription_management.xml",
        "views/service/medicine_classification.xml",
        "views/service/diagnosis_category.xml",
        "views/service/snomed.xml",
        "views/service/inherit_loyalty_program.xml",
        "views/service/favourite_products.xml",
        "views/service/product_branch_configuration.xml",
        "views/patient_category_views.xml",
        "wizard/xml/payer/create_payer_user_wizard_views.xml",
        "views/payer/payer_company.xml",
        "views/payer/payer_company_users.xml",
        "views/payer/payer_contract.xml",
        "views/payer/payer_policy.xml",
        "views/payer/payer_template.xml",
        "views/payer/payer_policy_limit_views.xml",
        "views/service/medicine_prescription.xml",
        "views/service/medicine_prescription_dosage.xml",
        "views/service/prescription.xml",
        "views/service/product_consumption_template.xml",
        "views/registration_order_detail_views.xml",
        "views/res_groups.xml",
        "views/his_order_detail_view.xml",
        # product
        "views/product_drug_tab.xml",
        "views/sale_order_line_tree.xml",
        # SMS
        "views/external_message/send_message.xml",
        "views/external_message/message_log.xml",
        # reports
        "reports/emr_doc.xml",
        "reports/order_detail_paper_format.xml",
        "reports/order_detail_report.xml",
        "reports/order_detail_design.xml",
        "reports/account_report.xml",
        "views/reports/invoice_receipt_thermal.xml",
        "reports/cashier/paperformat_cash.xml",
        "reports/cashier/cashier_session_report_2v.xml",
        "reports/cashier/cashier_report_2v.xml",
        "reports/cashier/company_layout.xml",
        "reports/report_invoice_template.xml",
        "reports/prescription_management_paper_format.xml",
        "reports/prescription_management_report.xml",
        "reports/prescription_management_design.xml",
        "reports/report_cashier_check.xml",
        "reports/partner_payment_history.xml",
        # 'reports/sale_report.xml',
        # report views
        # "views/reports/daily_revenue.xml",
        # "views/reports/medicine_statistics.xml",
        # "views/reports/number_of_patients.xml",
        # "views/reports/performance_stat_by_department.xml",
        # "views/reports/revenue_by_doctor_department.xml",
        # "views/reports/total_patient_visit.xml",
        # "views/reports/daily_performance_departments.xml",
        # "views/reports/daily_performance_details.xml",
        "views/company.xml",
        # wizard
        "wizard/xml/refer_visits.xml",
        "wizard/xml/emr/report_lang_wizard.xml",
        "wizard/xml/account/select_cashier_session.xml",
        "wizard/xml/account/account_move_discount_wizard_view.xml",
        "wizard/xml/account/change_invoice_partner_wizard_view.xml",
        "wizard/xml/doctor/dashboard.xml",
        "wizard/xml/doctor/doctor_referral_html.xml",
        "wizard/xml/doctor/doctor_schedule_wizard.xml",
        "wizard/xml/doctor/doctor_working_periods_wizard.xml",
        "wizard/xml/doctor/doctor_schedule_select.xml",
        "wizard/xml/order/calculator_services.xml",
        "wizard/xml/order/add_from_template.xml",
        "wizard/xml/order/add_from_history.xml",
        "wizard/xml/order/clone_services_wizard.xml",
        "wizard/xml/order/doctor_schedule_select_in_order_detail.xml",
        "wizard/xml/order/detail_button_in_order_detail.xml",
        "wizard/xml/order/reset_service_wizard_view.xml",
        "wizard/xml/order/add_doctor_services.xml",
        "wizard/xml/order/order_print_wizard.xml",
        "wizard/xml/doctor/doctor_schedule_wizard_delete.xml",
        "wizard/xml/doctor/doctor_schedule_calendar.xml",
        "wizard/xml/doctor/doctor_consult_wizard.xml",
        "wizard/xml/save_as_consumption_template_wizard.xml",
        "wizard/xml/doctor/bulk_doctor_fee.xml",
        "wizard/xml/doctor/doctor_fee_wizard.xml",
        "wizard/xml/payment/payment_order_detail_wizard.xml",
        "wizard/xml/payment/order_invoice_receipt_wizard.xml",
        "wizard/xml/payment/invoice_pdf.xml",
        # "wizard/xml/payment/extra_amount.xml",
        "wizard/xml/payment/sale_order_wizard.xml",
        "wizard/xml/order/order_detail_pdf.xml",
        "wizard/xml/order/cancel_cause_order_detail.xml",
        "wizard/xml/order/order_detail_status_wizard.xml",
        "wizard/xml/search/comments_template.xml",
        "wizard/xml/order/doctor_client_window_diagnosis.xml",
        "wizard/xml/order/surgery_wizard.xml",
        "wizard/xml/order/order_detail_wizard.xml",
        "wizard/xml/order/client_basket_order_list.xml",
        "wizard/xml/order/client_recommended_basket.xml",
        "wizard/xml/order/doctor_client_detail_window.xml",
        "wizard/xml/order/doctor_recommended_order_wizard.xml",
        "wizard/xml/order/consulted_doctor_order_wizard.xml",
        "wizard/xml/service/service_wizard.xml",
        "wizard/xml/payment/payment_wizard.xml",
        "wizard/xml/payment/share_bonus_edit_wizard.xml",
        "wizard/xml/patient/identifying_similar_patients.xml",
        "wizard/xml/patient/ambulatory_list_filter.xml",
        "wizard/xml/patient/print_emr_docs.xml",
        "wizard/xml/patient/patient_registration.xml",
        "wizard/xml/patient/debt_sale_order_line_html.xml",
        "views/payment/control_patient_money.xml",
        "wizard/xml/nurses/ambulatory_care_nurse.xml",
        "wizard/xml/nurses/patient_body_measurement.xml",
        "wizard/xml/payment/cancel_invoice_wizard.xml",
        "wizard/xml/warning_messages.xml",
        "wizard/xml/doctor/doctor_share_and_bonus_view.xml",
        # patient total view
        "wizard/xml/patient_total_view/main.xml",
        "wizard/xml/patient_total_view/payer_policy.xml",
        "wizard/xml/patient_total_view/invoice.xml",
        "wizard/xml/patient_total_view/history_of_illness.xml",
        "wizard/xml/patient_total_view/order_results.xml",
        # "wizard/xml/patient_total_view/wallet.xml",
        "wizard/xml/patient_total_view/my_recommendations.xml",
        "wizard/xml/patient_total_view/visit.xml",
        "wizard/xml/patient_total_view/notifications.xml",
        "wizard/xml/patient_total_view/file.xml",
        "wizard/xml/patient_total_view/to_do.xml",
        "wizard/xml/patient_total_view/diagnosis.xml",
        # insurance
        # "wizard/xml/insurance/upload_insurance_patients.xml",
        # payer
        "wizard/xml/payer/payer_contract_wizard.xml",
        # "wizard/xml/reports/reports_category.xml", keyinroq yana ko'rib chiqiladi
        "wizard/xml/emr/user_emrs_wizard_views.xml",
        "wizard/xml/emr/emr_templates_wizard.xml",
        "wizard/xml/emr/emr_template.xml",
        "wizard/xml/emr/patient_visit_emr_create.xml",
        "wizard/xml/emr/doctor_emr_auto_fields.xml",
        # search Wizard
        "wizard/xml/search/outpatient_search.xml",
        "wizard/xml/search/daily_revenue_search.xml",
        "wizard/xml/search/med_class_search.xml",
        "wizard/xml/search/medicine_statistics_search.xml",
        "wizard/xml/search/number_of_patients_search.xml",
        "wizard/xml/search/performance_stat_by_department_search.xml",
        "wizard/xml/search/revenue_by_doctor_department_search.xml",
        "wizard/xml/search/total_patient_visit_search.xml",
        "wizard/xml/search/pres_management.xml",
        # product
        "wizard/xml/product/doctors_list_wizard.xml",
        "wizard/xml/product/product_product_pdf.xml",
        "wizard/xml/product/product_calculate.xml",
        # emr
        "views/emr/emr_draft.xml",
        "views/emr/emr_pdf_viewer.xml",
        "views/emr/report_report.xml",
        # automation
        "automation/calculate_doctor_share.xml",
        "automation/calculate_referal_bonus.xml",
        "automation/recalculate_sale_order_line_price.xml",
        "automation/manage_product_website_fields.xml",
        "automation/hide_menu_for_group.xml",
        "automation/recompute_priceline_all_day.xml",
        "automation/patient_visit_cancelled.xml",
        "automation/order_detail_done_consulted.xml",
        "automation/order_detail_delayed_scheduler.xml",
        "automation/recompute_visit_debt.xml",
        "automation/undo_done.xml",

        # 'automation/refresh_views.xml',
        # utils
        "utils/pdf_viewer/view.xml",
        "utils/attachment_viewer/view.xml",
        "views/ir_attachment.xml",
        "utils/html_viewer/view.xml",
        # res_config
        # "views/res_config.xml",
        # branch
        "views/res_company.xml",
        "views/res_partner.xml",
        "views/res_bank.xml",
        "views/res_partner_bank.xml",
        "views/his_referral_source_by_service_views.xml",
        "views/his_referral_source_by_product_type_views.xml",
        "views/his_referral_source_by_product_category_views.xml",
        # cashier
        "views/cashier/cash_register.xml",
        "views/cashier/cashier_session.xml",
        "views/cashier/cashier_session_report_views.xml",
        "views/cashier_session_wizard.xml",
        "wizard/xml/cashier/close_pos_popup.xml",
        "views/cashier/cashier_invoice.xml",
        "views/cashier/cashier_payments.xml",
        "wizard/xml/cashier/top_up_reduce_cashier_balance.xml",
        "views/service/medicine_prescription_cancel_reson.xml",
        "wizard/xml/service/medicine_prescription_cancel_form.xml",
        "wizard/xml/service/prescription_wizard.xml",
        "wizard/xml/calculate_services.xml",
        "wizard/xml/prescription_save_as_template_wizard.xml",
        "wizard/xml/prescription_medicine_save_as_template_wizard copy.xml",
        "wizard/xml/cashier/cash_in_out.xml",
        "views/res_config_settings.xml",
        "views/res_config_settings_account.xml",
        "wizard/xml/emr/multi_tab_report.xml",
        "wizard/xml/print_report_template_wizard.xml",
        # tier validation
        "views/tier_validation/tier_definition_view.xml",
        # indexes
        "data/TrgmIndex.xml",
        "data/config_parameters.xml",
        "data/cash_transfer_tier_definition.xml",
        "data/force_done_service.xml",

    ],
    "post_init_hook": "post_init_hook",
    "application": True,
    "installable": True,
    "assets": {
        "web.assets_backend": [
            "his/static/src/scss/*.scss",
            "his/static/src/js/favicon.js",
        ],
    },
}
