from datetime import timedelta
from odoo import models, fields, api, exceptions, _
from odoo.osv import expression


class PayerPolicy(models.Model):
    _name = "his.payer_policy"
    _inherit = "mail.thread"
    _description = "Payer Policy Records"
    _rec_name = "policy_number"

    full_name = fields.Char(string="Full Name", required=True)
    passport_serial = fields.Char(string="Passport Serial")
    phone_number = fields.Char(string="Phone Number")
    pinfl = fields.Char(string="PINFL")
    birth_date = fields.Date(string="Birth Date")
    gender = fields.Selection(
        [
            ("male", "Male"),
            ("female", "Female"),
        ],
        string="Gender",
        default="male",
    )
    contract_id = fields.Many2one("his.payer_contract")
    payer_company_id = fields.Many2one(
        "his.payer_company", required=True, tracking=True
    )
    patient_id = fields.Many2one("his.patient", tracking=True)
    policy_number = fields.Char(string="Policy Number", required=True, tracking=True)
    policy_amount = fields.Float(string="Policy Amount", tracking=True)
    from_date = fields.Date(
        string="From Date", required=True, default=fields.Date.today
    )
    to_date = fields.Date(
        string="To Date",
        required=True,
        default=lambda self: fields.Date.today() + timedelta(days=30),
        tracking=True,
    )
    is_active = fields.Boolean(string="Active", default=True, tracking=True)
    template_id = fields.Many2one("his.payer_template")
    template_domain = fields.Binary(compute="_compute_template_domain")
    is_readonly = fields.Boolean(string="Readonly", default=False)
    payer_policy_limit_ids = fields.One2many(
        "his.payer_policy_limit", "policy_id", string="Policy Limits", tracking=True
    )
    used_amount = fields.Float(
        string="Used Amount", compute="_compute_used_amount", store=False
    )
    balance = fields.Float(
        string="Balance", compute="_compute_used_amount", store=False
    )
    is_autogenerated = fields.Boolean(string="Autogenerated")

    _sql_constraints = [
        (
            "unique_policy_number_per_company",
            "unique(policy_number, payer_company_id)",
            "The policy number must be unique per payer branch.",
        )
    ]

    def _compute_used_amount(self):
        """Ishlatilgan summani read_group orqali hisoblash"""
        # TODO limit faqat bitta vizit uchun qulanilgani uchun bu logika to'g'ri ishlamaydi
        for record in self:
            result = self.env["sale.order.line"].read_group(
                domain=[("payer_policy", "=", record.id), ("state", "=", "sale")],
                fields=["coverage_amount:sum"],
                groupby=[],
            )
            record.used_amount = result[0]["coverage_amount"] if result else 0.0
            record.balance = record.policy_amount - record.used_amount

    @api.model
    def default_get(self, fields_list):
        defaults = super(PayerPolicy, self).default_get(fields_list)
        active_id = self.env.context.get("active_id", False)
        payer_company_id = self.env.context.get("payer_company_id", False)
        if self.env.context.get("active_model") == "his.patient_visit":
            patient_visit = self.env["his.patient_visit"].browse(active_id)
            defaults.update(
                {
                    "patient_id": patient_visit.patient_id.id,
                    "full_name": patient_visit.patient_id.full_name,
                    "birth_date": patient_visit.patient_id.date,
                    "pinfl": patient_visit.patient_id.pinfl,
                    "phone_number": patient_visit.patient_id.phone_number,
                    "passport_serial": patient_visit.patient_id.passport_serial,
                    "payer_company_id": payer_company_id,
                    "is_readonly": True,
                }
            )
        return defaults

    # type = fields.Selection(
    #     [("direct_access", "Direct Access"), ("temporary_certificate", "Temporary Certificate"),
    #      ("default", "Default")], string="Type"
    # )
    @api.onchange("contract_id")
    def _onchange_contract_id(self):
        if self.contract_id:
            self.template_id = self.contract_id.template_id.id

    @api.depends("payer_company_id")
    def _compute_template_domain(self):
        for rec in self:
            if rec.payer_company_id.exists():
                rec.template_domain = [
                    ("id", "in", rec.payer_company_id.template_ids.ids)
                ]
            else:
                rec.template_domain = [("id", "=", False)]

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get("contract_id") and not vals.get("payer_company_id"):
                vals["payer_company_id"] = (
                    self.env["his.payer_contract"]
                    .browse(vals.get("contract_id"))
                    .payer_company_id.id
                )
        return super(PayerPolicy, self).create(vals_list)

    @api.model
    def _name_search(self, name="", args=None, operator="ilike", limit=1000):
        if args is None:
            args = []  # Ensure args is initialized as an empty list if None

        args.append(["to_date", ">=", fields.Date.today()])

        if name:
            args.append(["policy_number", "ilike", name + "%"])

        return self._search(args, limit=limit)

    def identifying_similar_patients(self):
        if self.patient_id.exists():
            raise exceptions.ValidationError(_("This policy is already connected to a patient"))
        trgm_limit = self.env[
            "his.patient"
        ]._get_identifying_similar_patients_trgm_limit()
        # birth_date is a strong dedup key — when present, loosen the name match
        # (lower min_matches) so spelling variations still surface the duplicate.
        # pinfl is handled separately via the OR branch below, so only birth_date
        # drives the threshold here. Both thresholds are tunable via Settings.
        Patient = self.env["his.patient"]
        has_strong_key = bool(self.birth_date)
        name_domain = Patient._search_patient_domain(
            self.full_name,
            limit=trgm_limit,
            min_matches=Patient._get_identifying_similar_patients_min_matches(
                has_strong_key
            ),
        )
        if name_domain and self.birth_date:
            name_domain += [("date", "=", self.birth_date)]
        # pinfl is an even stronger key — OR it with the name-based branch so
        # a pinfl match alone surfaces the patient even if the name differs.
        # Use expression.OR to handle the case where name_domain is empty
        # (e.g. empty full_name + no birth_date) — manual ["|", ...] would
        # produce invalid polish notation.
        parts = []
        if self.pinfl:
            parts.append([("pinfl", "=", self.pinfl)])
        if name_domain:
            parts.append(name_domain)
        if not parts:
            return []
        domain = expression.OR(parts) if len(parts) > 1 else parts[0]
        return self.env["his.patient"].search(domain).ids

    def action_match_and_connect(self):
        similar_patients = self.identifying_similar_patients()
        if similar_patients:
            action = {
                "type": "ir.actions.act_window",
                "name": "Search Patient",
                "res_model": "his.identifying_similar_patients",
                "view_mode": "form",
                "views": [
                    (
                        self.env.ref(
                            "his.view_identifying_similar_patients_policy_form"
                        ).id,
                        "form",
                    )
                ],
                "context": {"default_patient_ids": [(6, 0, similar_patients)]},
                "target": "new",
            }
            return action
        else:
            full_name = self.full_name.split(" ")
            patient = self.env["his.patient"].create(
                {
                    "first_name": full_name[0] if len(full_name) >= 1 else "",
                    "last_name": full_name[1] if len(full_name) >= 2 else "",
                    "middle_name": full_name[2] if len(full_name) >= 3 else "",
                    "passport_serial": self.passport_serial,
                    "phone_number": self.phone_number,
                    "pinfl": self.pinfl,
                    "date": self.birth_date,
                    "name": self.full_name,
                }
            )
            self.patient_id = patient.id
            return {
                "type": "ir.actions.client",
                "tag": "show_alert_dialog",
                "params": {
                    "title": _("Success"),
                    "message": _("New Patient Created and Connected"),
                    "type": "success",
                    "sticky": False,
                    "next": {
                        "type": "ir.actions.act_window_close",
                        "tag": "soft_reload",
                    },
                },
            }

    def action_delete(self):
        self.is_active = False

    def action_restore(self):
        self.is_active = True

    def action_create_and_add_to_registration(self):
        if not self.env.context.get("registration_id"):
            raise exceptions.ValidationError(_("Registration ID is not provided"))
        registration_id = self.env["his.patient_registration"].browse(
            self.env.context.get("registration_id")
        )
        if not registration_id.payer_company_id:
            registration_id.write(
                {
                    "coverer_type": self.payer_company_id.cooperation_type,
                    "payer_company_id": self.payer_company_id.id,
                }
            )
        registration_id.write(
            {
                "payer_policy": self.id,
            }
        )
        view_id = self.env.ref("his.view_patient_registration_form").id
        return {
            "type": "ir.actions.act_window",
            "name": _("Patient Registration"),
            "res_model": "his.patient_registration",
            "view_mode": "form",
            "view_id": view_id,
            "res_id": registration_id.id,
            "target": "main",
        }

    def action_create_and_add_to_patient_visit(self):
        if not self.env.context.get("patient_visit_id"):
            raise exceptions.ValidationError(_("Patient Visit ID is not provided"))
        patient_visit_id = self.env["his.patient_visit"].browse(
            self.env.context.get("patient_visit_id")
        )
        if not patient_visit_id.payer_company_id:
            patient_visit_id.write(
                {
                    "coverer_type": self.payer_company_id.cooperation_type,
                    "payer_company_id": self.payer_company_id.id,
                }
            )
        patient_visit_id.write(
            {
                "payer_policy": self.id,
            }
        )
        view_id = self.env.ref("his.view_patient_visit_form").id
        return {
            "type": "ir.actions.act_window",
            "name": _("Patient Registration"),
            "res_model": "his.patient_registration",
            "view_mode": "form",
            "view_id": view_id,
            "res_id": patient_visit_id.id,
            "target": "current",
            "replace_breadcrumb": True,
        }

    def action_create_and_add_to_sale_order_wizard(self):
        if not self.env.context.get("sale_order_wizard_id"):
            raise exceptions.ValidationError(_("Patient Visit ID is not provided"))
        sale_order_wizard_id = self.env["his.sale_order_wizard"].browse(
            self.env.context.get("sale_order_wizard_id")
        )
        if not sale_order_wizard_id.payer_company_id:
            sale_order_wizard_id.write(
                {
                    "coverer_type": self.payer_company_id.cooperation_type,
                    "payer_company_id": self.payer_company_id.id,
                }
            )
        sale_order_wizard_id.write(
            {
                "payer_policy": self.id,
            }
        )
        return {
            "type": "ir.actions.act_window",
            "name": "New Sale Order/Invoice",
            "res_model": "his.sale_order_wizard",
            "view_mode": "form",
            "res_id": sale_order_wizard_id.id,
            "target": "new",
        }
